# Generated by Django 2.0.6 on 2020-03-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
                ('gender', models.BooleanField()),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('phone', models.IntegerField(max_length=11)),
                ('address', models.CharField(max_length=255)),
                ('head_img', models.CharField(max_length=255)),
                ('brief', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
